290323creating dbobjects
all-news-project/server pull request #17
Opened 2023-04-03 07:18 UTC by TalSomech

2023-04-04 06:21 UTC, kggold4 requested changes

2023-04-10 06:58 UTC, TalSomech commented on db_utils/db_objects/db_objects_utils.py
> +
change the update and create cluster but will change the article after scraping component

2023-04-22 10:03 UTC, TalSomech commented on db_utils/db_objects/db_objects_utils.py
> +    db.update_one("clusters", {"cluster_id", cluster.cluster_id},
i have added data filter and new data but the table name should always be clusters since its the update cluster function

2023-05-17 17:04 UTC, kggold4 commented on nlp_models/nlp_utils/cluster_utils.py
> +def _check_avg_cluster_sim(cluster: Cluster, new_article: Article):
Give `id's` not objects

2023-05-17 17:04 UTC, kggold4 commented on nlp_models/nlp_utils/cluster_utils.py
> +    avg_rate = avg_rate / len(articles)
What this function return / do?

2023-05-17 17:04 UTC, kggold4 commented on nlp_models/nlp_utils/nlp_utils.py
> +# To determine whether two texts are written about the same subject using natural language processing (NLP) techniques, you can use a text similarity model. This type of model takes two texts as inpu
This file is needed?
Make in class

2023-05-17 17:04 UTC, kggold4 commented on nlp_models/temp
> +To determine whether two texts are written about the same subject using natural language processing (NLP) techniques, you can use a text similarity model. This type of model takes two texts as input
temp file need to be deleted or be in the `.gitignore` file

2023-05-17 17:04 UTC, kggold4 commented on nlp_models/similizer_test.py
> +import unittest
Need more working tests, not comments, create only few simple tests for now and check with db

2023-05-17 17:04 UTC, kggold4 commented on nlp_models/tests/test_nlp_article.py
> +import unittest
Need more working tests, not comments, create only few simple tests for now and check with db

2023-05-17 17:04 UTC, kggold4 commented on nlp_models/tests/test_nlp_utils.py
> +import unittest
Need more working tests, not comments, create only few simple tests for now and check with db

2023-05-17 17:06 UTC, kggold4 commented
Mabye all the nlp tests files should be in one file?

2023-07-30 18:09 UTC, kggold4 commented on nlp_models/model_nlp/model_nlp.py
> +    # def check_similarity(self):
delete comments

2023-07-30 18:09 UTC, kggold4 commented on nlp_models/model_nlp/model_nlp.py
> +        # nltk.download('stopwords')
delete comments

2023-07-30 18:09 UTC, kggold4 commented on nlp_models/nlp_utils/consts.py
> +class NlpConsts:
move to `test` folder

2023-07-30 18:09 UTC, kggold4 commented on nlp_models/nlp_utils/nlp_utils.py
> +    def summarize(self, content: str) -> str:
Check if getting all the cluster articles content and summarize using PRIMER (multi-document summarizer)

2023-07-30 18:09 UTC, kggold4 commented on nlp_models/nlp_utils/nlp_utils.py
> +        # if res > 0.90 and abs(
delete comments

2023-07-30 18:09 UTC, kggold4 commented on nlp_models/temp
> +To determine whether two texts are written about the same subject using natural language processing (NLP) techniques, you can use a text similarity model. This type of model takes two texts as input
delete file

2023-08-01 07:05 UTC, kggold4 approved these changes

2023-08-01 07:17 UTC, merged